### ISSUE TITLE
Review Jitbit fixes Dec 2018-April 2019

### ISSUE THREAD

**Issue by martin-displayr** [Displayr/AspNetSaml#6]
There are some fixes for security, etc. on the original Jitbit branch since we forked. https://github.com/jitbit/AspNetSaml/commits/master. Review these and merge in as applicable. Since there is now some divergence these would probably need to be manually applied.

**Comment by Benjamin-Displayr** [comment]
In the commit (https://github.com/Displayr/AspNetSaml/commit/84913d45066d61541ef8f37a95e51d90428051eb) I brought all the changes from the original repo into this repo.
